name: Aternos Bedrock AFK Bot

on:
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Kodni yuklash
        uses: actions/checkout@v4

      - name: Node.js o'rnatish
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Bedrock kutubxonasini o'rnatish
        run: npm install bedrock-protocol

      - name: Botni ishga tushirish
        run: node bot.js
        
