const mineflayer = require('mineflayer');

function createBot() {
    const bot = mineflayer.createBot({
        host: 'Uzlegend2.aternos.me',
        port: 50273,
        username: 'AFK_Bot'
    });

    bot.on('login', () => {
        console.log('Bot serverga muvaffaqiyatli kirdi!');
    });

    bot.on('end', () => {
        console.log('Bot uzildi, qayta ulanmoqda...');
        setTimeout(createBot, 5000);
    });

    bot.on('error', (err) => {
        console.log('Xatolik:', err);
    });
}

createBot();
